version: '3.8'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  redis-aof:
    driver: ${VOLUMES_DRIVER}
  redis-rdb:
    driver: ${VOLUMES_DRIVER}
services:
  redis-aof:
    build:
      context: ./docker/redis-aof
    container_name: redis-aof
    volumes:
      - ./volume/data/redis-aof:/data
    ports:
      - "${REDIS_AOF_PORT}:6379"
    networks:
      - backend
  redis-rdb:
    build:
      context: ./docker/redis-rdb
    container_name: redis-rdb
    volumes:
      - ./volume/data/redis-rdb:/data
    ports:
      - "${REDIS_RDB_PORT}:6379"
    networks:
      - backend
  beanstalkd:
    build: ./docker/beanstalkd
    container_name: beanstalkd
    ports:
      - "${BEANSTALKD_PORT}:11300"
    depends_on:
      - php-fpm
    networks:
      - backend
  beanstalkd-console:
    build:
      context: ./docker/beanstalkd-console
      args:
        - BEANSTALKD_PORT_11300_TCP_ADDR=${BEANSTALKD_HOST}
    container_name: beanstalkd-console
    ports:
      - "${BEANSTALKD_CONSOLE_HOST_PORT}:2080"
    depends_on:
      - beanstalkd
    networks:
      - backend
  php-fpm:
    build:
      context: ./docker/php-fpm
    container_name: php-fpm
    depends_on:
      - redis-aof
      - redis-rdb
    environment:
      - REDIS_AOF_HOST=${REDIS_AOF_HOST}
      - REDIS_AOF_PORT=${REDIS_AOF_PORT}
      - REDIS_RDB_HOST=${REDIS_RDB_HOST}
      - REDIS_RDB_PORT=${REDIS_RDB_PORT}
      - BEANSTALKD_HOST=${BEANSTALKD_HOST}
      - BEANSTALKD_PORT=${BEANSTALKD_PORT}
      - APP_ENV=${APP_ENV}
    expose:
      - "9000"
    volumes:
      - ./application:/var/www/html
    networks:
      - backend
  nginx:
    build:
      context: ./docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    container_name: nginx
    restart: always
    volumes:
      - ./application:/var/www/html
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./volume/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    networks:
      - backend
      - frontend
